"""empty message

Revision ID: 4f63906bea97
Revises: 48ebdd9fc1f6
Create Date: 2026-05-26 21:11:34.341727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f63906bea97'
down_revision: Union[str, Sequence[str], None] = '48ebdd9fc1f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('marketplace', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'marketplace')
    # ### end Alembic commands ###
