"""add column product_name



Revision ID: 7b1de1f4a4f1
Revises: a13a3c2b342b
Create Date: 2026-06-25 22:53:54.848830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b1de1f4a4f1'
down_revision: Union[str, Sequence[str], None] = 'a13a3c2b342b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('article', sa.String(), nullable=True))
    op.add_column('products', sa.Column('product_name', sa.String(), nullable=True))
    op.drop_column('products', 'product_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('product_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('products', 'product_name')
    op.drop_column('products', 'article')
    # ### end Alembic commands ###
